### ISSUE TITLE
选择区域没有触发change事件，能加一下吗

### ISSUE THREAD

**Issue by qingshangyun** [halobear/npm-packages#3]

**Comment by kuan1** [comment]
这里是选择地区的组件的demo页面 [点击查看](https://halobear.github.io/npm-packages/vue-region/demo.html)

上边的demo页面是可以监听到change事件的，你看一下demo页面的代码  [点击查看](https://github.com/halobear/npm-packages/blob/master/docs/.vuepress/components/vue-region.vue)
